
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOTH_BRACKETS = 33;
  public static final int BOTH_BRACES = 36;
  public static final int GTEQ = 52;
  public static final int LTEQ = 50;
  public static final int DEVIDE = 47;
  public static final int doubleConstant = 60;
  public static final int DOUBLE = 21;
  public static final int SEMI = 41;
  public static final int PARENTHESES_OPEN = 37;
  public static final int PRIVATE = 5;
  public static final int CONTINUE = 16;
  public static final int INTERFACE = 9;
  public static final int INT = 20;
  public static final int intConstant = 59;
  public static final int MINUS = 45;
  public static final int FOR = 13;
  public static final int stringConstant = 62;
  public static final int dtoi = 28;
  public static final int NOT = 57;
  public static final int AND = 55;
  public static final int LT = 49;
  public static final int OR = 56;
  public static final int BOOL = 22;
  public static final int CLASS = 6;
  public static final int itod = 27;
  public static final int boolConstant = 61;
  public static final int itob = 29;
  public static final int PLUS = 44;
  public static final int IF = 10;
  public static final int THIS = 19;
  public static final int DOT = 43;
  public static final int btoi = 30;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int ReadInteger = 24;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int BRACKETS_CLOSE = 32;
  public static final int NULL = 64;
  public static final int EQEQ = 53;
  public static final int MOD = 48;
  public static final int BOTH_PARENTHESES = 39;
  public static final int PARENTHESES_CLOSE = 38;
  public static final int IDENT = 63;
  public static final int BREAK = 15;
  public static final int VOID = 3;
  public static final int BRACES_OPEN = 34;
  public static final int EQ = 58;
  public static final int NewArray = 26;
  public static final int TIMES = 46;
  public static final int COLON = 42;
  public static final int ELSE = 11;
  public static final int PROTECTED = 7;
  public static final int WHILE = 12;
  public static final int PUBLIC = 8;
  public static final int EXTENDS = 2;
  public static final int STRING = 23;
  public static final int GT = 51;
  public static final int BRACES_CLOSE = 35;
  public static final int readLine = 25;
  public static final int IMPLEMENTS = 4;
  public static final int PRINT = 17;
  public static final int BRACKETS_OPEN = 31;
  public static final int NOTEQ = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXTENDS",
  "VOID",
  "IMPLEMENTS",
  "PRIVATE",
  "CLASS",
  "PROTECTED",
  "PUBLIC",
  "INTERFACE",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "PRINT",
  "NEW",
  "THIS",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "ReadInteger",
  "readLine",
  "NewArray",
  "itod",
  "dtoi",
  "itob",
  "btoi",
  "BRACKETS_OPEN",
  "BRACKETS_CLOSE",
  "BOTH_BRACKETS",
  "BRACES_OPEN",
  "BRACES_CLOSE",
  "BOTH_BRACES",
  "PARENTHESES_OPEN",
  "PARENTHESES_CLOSE",
  "BOTH_PARENTHESES",
  "COMA",
  "SEMI",
  "COLON",
  "DOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DEVIDE",
  "MOD",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "EQEQ",
  "NOTEQ",
  "AND",
  "OR",
  "NOT",
  "EQ",
  "intConstant",
  "doubleConstant",
  "boolConstant",
  "stringConstant",
  "IDENT",
  "NULL"
  };
}

